name: "${name}"
version: "${version}"
main: "${group}.${name}Main"
description: "${description}"
api-version: '${api}'
author: Wida
softdepend: ["PlaceholderAPI", "LuckPerms"]

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.0.0
  - org.jetbrains.kotlin:kotlin-reflect:2.0.0

permissions:
  tnt.iamallowedtodospectatorbecauseiamcoolaf: